baseURL = '/'
languageCode = 'en-id'
title = 'Shopping Fair'
theme = 'ignatha'

[params]
  fb_pixel = '858533401898466'

[minify]
    minifyOutput = true

[minify.tdewolff.html]
  keepWhitespace = false